#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "117.16.244.185";
$SERVER_PORT = 22011;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
